version: '3'                    # Version for docker-compose interpreter
services:                       # Dictionnary of services to run
  node:                         # Name of the service
    build:                      # Define how to build the image "dojo-docker:1.0.0" if the image is not found in local docker image repo
      context: .
      dockerfile: Dockerfile
    image: dojo-docker:1.0.0    # The name of the image to run
    ports:
      - 3128:3000               # Map host port 3128 to container port 3000

  mongodb:
    image: mongo:4.2.8-bionic
    volumes:
      - ./mongodb-data:/data/db # Bind host directory ./mongodb-data to container directory /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dojo
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports:
      - "27128:27017"
